### PR TITLE
modified backend crreate task to return task not goal object

### PR DESCRIPTION
**Pull request by Tshimangadzo**

### CODE REVIEW

**Review by nhlamulo-maluleka — COMMENTED** [review]
Not sure if its me, but after a new goal task is added, the returning task object has an invalid goalId. 

image

**Comment by Tshimangadzo** [comment]
Hi @nhlamulo-maluleka 

I realized that we are not using that goal ID; I didn't see a reason to include it.

**Comment by Tshimangadzo** [comment]
## Added goal Id

added_goalId

## Fixed Archiving issue #61 
two_goals_completed

db_completed


two_archived_goal_uncompleted

task_uncompleted

two_goals_started_again_uncompleted

**Comment by nhlamulo-maluleka** [comment]
Hi @Tshimangadzo 

Can you also capture the comments themselves on the database? - They are still not reflected on the comment table

**Comment by Tshimangadzo** [comment]
> Hi @Tshimangadzo
> 
> Can you also capture the comments themselves on the database? - They are still not reflected on the GoalComment table

Yes, I have created an issue for that, I am busy with it. For now, review this issue #61 and #67

**Comment by Tshimangadzo** [comment]
@nhlamulo-maluleka 

I didn't include the remove and edit comment functionalities ideally. The front end does not respond to comment responses. I am returning the GoalCommentModel to the front end.

**Review by sallie325 — APPROVED** [review]

**Review by Fernando-Shilenge — APPROVED** [review]

**Pull request merged**
